// examples/vue-app/src/App.vue
<script setup>
import { AppRoutes } from './routes';
import Footer from './components/Footer.vue';
</script>

<template>
  <div class="container">
    <header class="app-header">
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src="/vite.svg" class="logo" alt="Vite logo" />
        </a>
        <a href="https://vuejs.org/" target="_blank">
          <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
        </a>
      </div>

      <nav class="app-nav">
        <router-link v-for="route in AppRoutes" :key="route.path" :to="route.path">
          {{ route.name }}
        </router-link>
      </nav>
    </header>
  </div>
  <main class="container my-4">
    <router-view></router-view>
  </main>
  <Footer />
  <it-back-to-top it-aria-label="Torna su"></it-back-to-top>
</template>

<style>
section {
  margin: 4rem 0;
}
.flex {
  display: flex;
  align-items: start;
  padding: 0.3rem 0;
  gap: 0.6rem;
}
</style>
<style scoped>
.app-header {
  border-bottom: 1px solid currentColor;
  margin-bottom: 2rem;
  text-align: center;
}
.app-nav {
  display: flex;
  justify-content: center;
  gap: 1rem;
  margin: 1rem 0;
}

.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// examples/react-app/src/App.jsx
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import { AppRoutes } from './routes';
import { Footer } from './components/Footer';
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
import './App.css';

function App() {
  return (
    <BrowserRouter basename="react-app">
      <header className="app-header">
        <div>
          <a href="https://vite.dev" target="_blank">
            <img src={viteLogo} className="logo" alt="Vite logo" />
          </a>
          <a href="https://react.dev" target="_blank">
            <img src={reactLogo} className="logo react" alt="React logo" />
          </a>
        </div>
        <div class="container">
          <div>Vite + React</div>
          <nav className="app-nav">
            {AppRoutes.map((route) => (
              <Link key={route.path + 'link'} to={route.path}>
                {route.title}
              </Link>
            ))}
          </nav>
        </div>
      </header>
      <main className="container mb-4">
        <Routes>
          {AppRoutes.map((route) => (
            <Route key={route.path} path={route.path} element={route.element} />
          ))}
        </Routes>
      </main>
      <Footer />
      <it-back-to-top it-aria-label="Torna su"></it-back-to-top>
    </BrowserRouter>
  );
}

export default App;
